### PR TITLE
Update locales.dart

### PR DESCRIPTION
**Pull request by wickdj**
Added hu language.

### CODE REVIEW

**Comment by deckerst** [comment]
Oops, I've just realized I forgot to disable the Hungarian language in the latest release of Aves.

Normally I enable a new language in the app when the translation reaches 90% completion. When it does, i take care of integration in the app.

By the way, thanks for your contributions on weblate!

**Comment by wickdj** [comment]
Hi! I crossed over 90% on weblate. In the next few days I want to reach 100%.

**Comment by deckerst** [comment]
Thanks, that's great! I'll take a look to approve it (checking format, etc.) and take care of integrating it in the app.
Also, I'll add you as a super-user for Hungarian so you can approve and manage translations on weblate.

**Comment by deckerst** [comment]
Nice, thanks again!

I'm taking a look now. One little thing I noticed: for plurals, like `{count, plural, =1{1 column} other{{count} columns}}`:
- if there's no variation in Hungarian, you don't need to put all variants like `{count, plural, =1{1 oszlop} other{{count} oszlop}}`, you can simplify as `{count, plural, other{{count} oszlop}}`. I will fix them as I see them.
- if there's actually some variations but the format is confusing, please let me know and I can explain further.

**Comment by deckerst** [comment]
Another thing, I saw in your translations quoting with “option 1” (same as English) and „option 2”. The quotation marks for option 2 seem to be the proper ones in Hungarian, so I'll fix the others to be consistent.

**Pull request closed without merging**
