### PR TITLE
Update terms.md

### PR DESCRIPTION
**Pull request by p1gp1g**
Hello,

I have seen the issue following the application TOS and it is too bad if this great app is removed from F-Droid store for something that looks like a wording issue.

The suggested rewording in this PR should avoid issues pointed by some users. I hope you are ok with it. And I hope this doesn't consume too much of your time :)

Thanks again for your work !

(Ping @IzzySoft)

PS: The rewording has been suggested by someone on hackernews (https://news.ycombinator.com/item?id=34713852)

### CODE REVIEW

**Comment by deckerst** [comment]
Thanks! Fine with me. If the foss believers and f-droid people are happy with the new wording, let's merge it. Any representative can give a LGTM?

**Comment by p1gp1g** [comment]
It looks like this is a good solution for everyone :) (Heart reactions to your message and the answers on [gitlab/fdroiddata](https://gitlab.com/fdroid/fdroiddata/-/issues/2893#note_1272643289))

**Review by IzzySoft — COMMENTED** [review]
LGTM

**Comment by IzzySoft** [comment]
@deckerst "I agree" with your design – always did :smile: And honestly, switching the toggle on that… Well, actually I use paperclips for a lot of things they were not designed for, but I have no issues to "agree" they were originally designed for tucking paper staples :see_no_evil:

Thanks to both of you! Hopefully now everybody can relax and enjoy this great app.

**Pull request merged**
